version: '3'

services:
  db_auth:
    container_name: 'db_auth'
    ports:
      - "5432:5432"
    environment:
      - 'POSTGRES_USER=sa'
      - 'POSTGRES_PASSWORD=root'
    image: postgres:14.3-alpine
